ecosystem {
  no_update_news = true
  no_donation_nag = true
}

input {
    sensitivity = 0.5
    accel_profile = flat
    touchpad:natural_scroll = true

    # Keyboard
    kb_layout = pl
    numlock_by_default = true
    # kb_options=grp:win_space_toggle
}

general {
    layout = dwindle

    gaps_in = 4
    gaps_out = 4
    border_size = 1
    allow_tearing = true
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)
}

dwindle {
    smart_split = true
}

decoration {
    rounding = 5
    blur {
        enabled = true
        size = 3
        passes = 1
    }
}

# Gaming
windowrule {
    name = steam-dialog
    match:class = ^(steam)$
    match:title = negative:^(Steam)$
    float = on
}

windowrule {
    name = steam-games
    match:class = ^(steam_app_.*)$
    content = game
    immediate = on
    no_blur = on
    no_shadow = on
    rounding = 0
    workspace = 5
}

# Special
windowrule {
    name = float-magic
    match:workspace = special:magic
    float = on
}

windowrule {
    name = discord-magic
    match:class = ^(discord)$
    workspace = special:magic silent
    float = on
    size = (monitor_w/2) (monitor_h-32)
    move = (monitor_w/2) 32
}

# Popups
windowrule {
    name = firefox-pip
    match:title = ^(Picture-in-Picture)$
    match:class = ^(firefox)$
    content = video
    pin = on
    float = on
    size = 640 360
    move = (monitor_w-window_w-2) (32+2)
}

windowrule {
    name = waybar-tui-popups
    match:class = waybar.popup
    float = on
    size = 1280 720
    center = on
}
