hl.on("hyprland.start", function()
    hl.exec_cmd("uwsm-app -s s -t service -- waybar")
    hl.exec_cmd("uwsm-app -s s -t service -- swaync")
    hl.exec_cmd("uwsm-app -s s -t service -- elephant")
    hl.exec_cmd("uwsm-app -s s -t service -- hypridle")
    hl.exec_cmd("uwsm-app -s s -t service -- sway-audio-idle-inhibit")
    hl.exec_cmd("uwsm-app -s s -t service -- walker --gapplication-service")

    hl.exec_cmd("uwsm-app -s b -t service -- hyprpaper")
end)
